function handleException(error) {
    console.log(error)
}

export default handleException;